dist: trusty
sudo: true
language: python
services:
  - postgres

addons:
  postgresql: "9.5"
python:
  - "3.4"

before_install:
 - sudo apt-get update -q
install:
 - sudo apt-get install gettext python-lxml gcc cmake libgeos++-dev libgdal-dev libsparsehash-dev libboost-dev libbz2-dev zlib1g-dev libexpat1-dev libutfcpp-dev libosmpbf-dev libprotobuf-dev protobuf-compiler cmake-curses-gui
 - sudo apt-get install make libboost-python-dev
 - pip install pipenv
 - pipenv sync -d
 - pip install .
before_script:
  - sudo apt-cache search postgis
  - sudo apt-get install -y  postgresql-9.5-postgis-2.3
  - psql -c 'create database bard;' -U postgres -h localhost
script:
 - ./update_pot.sh
 - pipenv shell PYTHONPATH="." coverage run --include=bard/bard.py,bard/postgis.py,bard/models.py,bard/cli.py test/test.py && coverage report
 - pipenv shell coveralls
