dist: trusty
sudo: true
language: python
services:
  - postgres

addons:
  postgresql: "9.5"
python:
  - "2.7"
  - "3.4"

before_install:
 - sudo apt-get update -q
install:
 - sudo apt-get install gettext python-lxml gcc cmake libgeos++-dev libgdal-dev libsparsehash-dev libboost-dev libbz2-dev zlib1g-dev libexpat1-dev libutfcpp-dev libosmpbf-dev libprotobuf-dev protobuf-compiler cmake-curses-gui
 - sudo apt-get install make libboost-python-dev
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - pip install coveralls
 - pip install osmium
before_script:
  - sudo apt-cache search postgis
  - sudo apt-get install -y  postgresql-9.5-postgis-2.3
  - psql -c 'create database changewithin;' -U postgres -h localhost
  - psql -c "create extension postgis" -U postgres -h localhost -d changewithin
  - psql -f changewithin/schema.sql -U postgres -h localhost -d changewithin
script:
 - ./update_pot.sh
 - PYTHONPATH="." coverage run --include=bard/bard.py test/test.py && coverage report
 - coveralls
